version: '3.3'

networks:
  coexistnetwork:

services:  

  discovery:
    image: discovery   
    build: ./discovery
    container_name: discovery
    env_file: api.env
    ports:
      - '33001:33001'
    networks:
      - coexistnetwork
      
  identity:
    image: identity   
    build: ./Identity
    env_file: api.env
    ports:
      - '33002-33010:80'
    networks:
      - coexistnetwork
    depends_on:
      - discovery
      
      
  
      
      
      

