version: '3.3'

networks:
  coexistnetwork:

services:  

  gateway:
    image: gateway   
    build: ./gateway
    container_name: gateway
    env_file: api.env
    ports:
      - '33000:33000'
    networks:
      - coexistnetwork

  discovery:
    image: discovery   
    build: ./discovery
    container_name: discovery
    env_file: api.env
    ports:
      - '33001:33001'
    networks:
      - coexistnetwork
      
  identity:
    image: identity   
    build: ./Identity
    env_file: api.env
    container_name: identity
    environment:
      - INSTANCE_PORT=33002
    ports:
      - '33002:80'
    networks:
      - coexistnetwork
    depends_on:
      - discovery

  supplier:
    image: supplier   
    build: ./supplier
    container_name: supplier
    env_file: api.env
    ports:
      - '33011:33011'
    networks:
      - coexistnetwork
    depends_on:
      - discovery
      - identity
      
      
  
      
      
      

